### ISSUE TITLE
Using a custom UI can still result in hidden buttons

### ISSUE THREAD

**Issue by dstein766** [wsaunders1014/laptop-fix#1]
(First off - thanks for this fix!)  I'm using MythicUI, which adds some graphics around the dialog frames.  Those extra bits aren't fully accounted for by laptop-fix and as a result things like the Select File section are still cut off.  I would assume this could apply to other custom UIs.

To recreate:
1) Disable MythicUI.
2) Bring up file picker.  Looks great.
3) Enable MythicUI.
4) Bring up file picker.  Note that a couple of rows at the bottom of the window are still obscured.

**Comment by wsaunders1014** [comment]
Just uploaded v0.0.2 with fix for this issue. Thanks for reporting.
