### ISSUE TITLE
Token right-click doesn't work when laptop-fix enabled

### ISSUE THREAD

**Issue by dstein766** [wsaunders1014/laptop-fix#2]
Placeholder report for now while I work on isolating this better, but I've got a repeatable problem where enabling laptop-fix prevents me from right-clicking on tokens on the map (i.e. to popup the show/hide, conditions overlay selector, combat state toggler, etc.).  Turning off laptop-fix resolves this particular problem.  (A right-click is essentially a no-op.  Nothing happens.)

I have a lot of other add-ons in use and haven't yet been able to determine whether it is related to a specific add'l add-on, so work continues.  Opening this now in hopes other users may be able to contribute additional info before I'm able to narrow it down.

**Comment by dstein766** [comment]
OK.  This is happening with ONLY laptop-fix enabled. 
Foundry 0.6.6
DND5e 0.96

This is in both 0.1 and 0.2 of laptop-fix.

**Comment by wsaunders1014** [comment]
Hey, someone else reported this a few minutes ago. I have just pushed another update, 0.0.3 with the fix for that issue. Thanks for reporting though.

**Comment by wsaunders1014** [comment]
You may need to delete and reinstall mod to get 0.0.3 to show up.
