### ISSUE TITLE
Support for Find the Culprit

### ISSUE THREAD

**Issue by apoapostolov** [wsaunders1014/laptop-fix#4]
If Find the Culprit is active, form fixing is needed for the Manage Modules dialog. 

![image](https://user-images.githubusercontent.com/4083812/91866300-08250d80-ec7b-11ea-90c3-fe4ef34356b0.png)

**Comment by wsaunders1014** [comment]
Try 0.0.5 and reopen if you're still having issues.

**Comment by apoapostolov** [comment]
Same issue. @wsaunders1014 

![image](https://user-images.githubusercontent.com/4083812/91953849-f3dc2180-ed09-11ea-98c1-b11de97474a9.png)

**Comment by wsaunders1014** [comment]
Try 0.0.6 version
