### ISSUE TITLE
Truncated screen in Manage Modules with MythicUI and/or TidyUI

### ISSUE THREAD

**Issue by dstein766** [wsaunders1014/laptop-fix#6]
Slightly more complex interaction issue.

Using MythicUI and Tidy UI, the Manage Modules screen is slightly truncated.  Can only see the top 1/2 of the Save/Deactivate buttons w/o scrolling.

Using MythicUI (Tidy UI DISABLED), the two buttons are not visible w/o scrolling (assuming, of course, that you have enough modules installed to require scrolling).

Using TidyUI by itself = OK

Disable both = OK

**Comment by wsaunders1014** [comment]
Try 0.0.5 and reopen if you're still having issues.
