### ISSUE TITLE
Macro edit form mangled when laptop-fix enabled

### ISSUE THREAD

**Issue by dstein766** [wsaunders1014/laptop-fix#7]
Foundry 0.6.6
DND5e 0.96
laptop-fix 0.0.5
NO OTHER MODULES

Without laptop-fix:
![image](https://user-images.githubusercontent.com/24942951/92008597-38f95700-ecfc-11ea-8695-9e87c0e72833.png)

With laptop-fix:
![image](https://user-images.githubusercontent.com/24942951/92008629-44e51900-ecfc-11ea-8ba8-067cc05991b1.png)

**Comment by wsaunders1014** [comment]
Fixed in 0.0.6
