### ISSUE TITLE
Show Character Art breaks

### ISSUE THREAD

**Issue by dstein766** [wsaunders1014/laptop-fix#8]
Foundry 0.6.6
DND5e 0.96
laptop-fix 0.0.5
NO OTHER MODULES

Right-click any actor with Token and/or Character artwork in the Actor sidebar.
Select "View Character Artwork" or "View Token Artwork", as appropriate.
EXPECTED: Artwork window displays artwork.
ACTUAL: Artwork window displays blank screen.

**Comment by wsaunders1014** [comment]
Check out 0.0.6
